export const BEGIN_LOGIN_AUTH = 'BEGIN_LOGIN_AUTH';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_CHILD_SUCCESS = 'REGISTER_CHILD_SUCCESS';
export const REGISTER_CHILD_ERROR = 'REGISTER_CHILD_ERROR';
