export const BEGIN_LOGIN_AUTH = 'BEGIN_LOGIN_AUTH';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const GET_CHILD_LIST = 'GET_CHILD_LIST';
export const VALIDATE_USER = 'VALIDATE_USER';
export const DELETE_CHILD = 'DELETE_CHILD';

export const REGISTER_CHILD_SUCCESS = 'REGISTER_CHILD_SUCCESS';
export const REGISTER_CHILD_ERROR = 'REGISTER_CHILD_ERROR';
